import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Geologica, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import SmoothScroll from "@/components/Lazyscroll-component/SmoothScroll";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});
  
const geologica = Geologica({
  subsets: ["latin"],
  variable: "--font-geologica",
  weight: ["300", "400", "500", "600", "700"],
});

const libreBaskerville = Libre_Baskerville({
  subsets: ['latin'],
  variable: '--font-baskerville',
  weight: ['400', '700'],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
   robots: {
    index: false,
    follow: false,
    nocache: true,
    googleBot: {
      index: false,
      follow: false,
      noimageindex: true,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geologica.className} ${libreBaskerville.variable}`}
    >
      <body className="min-h-full flex flex-col"><Navbar/>
      <SmoothScroll/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
